export const ROUTES = {
	ROOT: '/',
	REGISTRATION: '/registration',
	LOGIN: '/login',
	PRIVACY_POLICY: '/privacy-policy',
	TERMS_OF_USE: '/terms-of-use',
	MAP: '/map',
	CHAT: '/chat',
	FRIENDS: '/friends',
	ACCESS_GEO: '/access-geo',
	ACCESS_GEO_ERROR: '/access-geo-error',
	PROFILE: '/profile',
	ACCESS_AGE: '/access-age',
	COMING_SOON: '/coming-soon',
};
